version: "3.9"

services:
  app:
    build: .
    container_name: easychat_app
    depends_on:
      - ollama
    volumes:
      - sqlite_data:/data

    environment:
      - ConnectionStrings__Default=Data Source=/data/app.db;Foreign Keys=True
    ports:
      - "3000:8080"


  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"

    # This script starts Ollama, waits 5 seconds for it to boot, pulls the model, then keeps running
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve &
        sleep 5
        ollama pull tinyllama
        wait


  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      TZ: "Australia/Brisbane"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  sqlite_data:
  ollama_data: